# Generated by Django 4.1.2 on 2022-10-19 17:44

from django.db import migrations, models
import utils.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "price",
                    models.FloatField(
                        validators=[utils.validators.validate_2_decimal_places]
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
